### ISSUE TITLE
Error: unexpected token 

### ISSUE THREAD

**Issue by irfanwv** [scotch-io/node-crud-course#1]
How to resolve
```
/opt/lampp/htdocs/node-crud-course/app/controllers/main.controller.js:4
  showHome: (req, res) => {
                       ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/lampp/htdocs/node-crud-course/app/routes.js:4:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/lampp/htdocs/node-crud-course/server.js:44:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by fcamichel** [comment]
update Node.js. See: http://node.green/#ES2015-functions-arrow-functions
